"""
Django settings for rec_platform project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Local development works without any configuration. In production (Railway) these come from
# environment variables: DJANGO_SECRET_KEY, DJANGO_DEBUG, DJANGO_ALLOWED_HOSTS, DATABASE_URL.
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

ON_RAILWAY = "RAILWAY_ENVIRONMENT" in os.environ

# Debug is on locally and off on Railway, unless DJANGO_DEBUG says otherwise
DEBUG = os.environ.get("DJANGO_DEBUG", "0" if ON_RAILWAY else "1") == "1"

_DEV_SECRET_KEY = "django-insecure-bkcf%5ju8w=+zu92%r5!sh&33eekc8_+0g1+^1&%kaur)v(-n5"
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", _DEV_SECRET_KEY)
if not DEBUG and SECRET_KEY == _DEV_SECRET_KEY:
    raise ImproperlyConfigured("Set the DJANGO_SECRET_KEY environment variable in production.")

# Railway sets RAILWAY_PUBLIC_DOMAIN (e.g. myapp.up.railway.app); extra hosts via DJANGO_ALLOWED_HOSTS
ALLOWED_HOSTS = ["localhost", "127.0.0.1"] + [
    host.strip()
    for host in [os.environ.get("RAILWAY_PUBLIC_DOMAIN", ""), *os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",")]
    if host.strip()
]
CSRF_TRUSTED_ORIGINS = [f"https://{host}" for host in ALLOWED_HOSTS if host not in ("localhost", "127.0.0.1")]

# Railway terminates HTTPS at its proxy and forwards plain HTTP
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # Project apps (owner in brackets, see docs/PLAN.md)
    "core",  # Joseph: shell, layout, PWA, i18n
    "candidates",  # Vidic: candidate CRUD
    "pricing",  # Teun: pricing engine + calculator
    "clients",  # Ivan: clients, vacancies, matching, AI advisor
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",  # serves /static/ in production
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.auth.middleware.LoginRequiredMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "rec_platform.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "core.context_processors.navigation",
                "core.context_processors.ui",
            ],
        },
    },
]

WSGI_APPLICATION = "rec_platform.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# Local: db.sqlite3. Railway: the Postgres plugin's DATABASE_URL.
DATABASES = {
    "default": dj_database_url.config(default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}", conn_max_age=600),
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = "en"

LANGUAGES = [
    ("en", "English"),
    ("nl", "Nederlands"),
]

LOCALE_PATHS = [BASE_DIR / "core" / "locale"]

TIME_ZONE = "Europe/Amsterdam"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
if not DEBUG:
    # Compressed files with content hashes in their names (cached forever); needs collectstatic
    STORAGES = {
        "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
        "staticfiles": {"BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage"},
    }

# Auth: the whole platform is recruiter-only (LoginRequiredMiddleware above)
LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "candidates:list"
LOGOUT_REDIRECT_URL = "login"

# AI advisor (Ivan): optional, falls back to rule-based ranking when unset
ANTHROPIC_MODEL = "claude-opus-5"

# Travel distance (Teun): OpenStreetMap Nominatim + OSRM require an identifying User-Agent
TRAVEL_API_USER_AGENT = (
    "TalentRate-hackathon/0.1 (+https://github.com/thumaman/coding_challenge)"
)


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    "default": {
        "BACKEND": "django.core.mail.backends.console.EmailBackend",
    },
}
