# Generated by Django 6.1.1 on 2026-10-01 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('industry', models.CharField(blank=True, max_length=100, verbose_name='industry')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='city')),
                ('contact_name', models.CharField(blank=True, max_length=150, verbose_name='contact name')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='contact email')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='city')),
                ('max_rate_per_hour', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='max client rate / hour (€)')),
                ('hours_per_week', models.PositiveSmallIntegerField(default=40, verbose_name='hours per week')),
                ('remote_days_allowed', models.PositiveSmallIntegerField(default=0, verbose_name='remote days allowed')),
                ('min_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='min salary / month (€)')),
                ('max_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='max salary / month (€)')),
                ('skills', models.TextField(blank=True, help_text='Comma separated', verbose_name='skills / keywords')),
                ('is_open', models.BooleanField(default=True, verbose_name='open')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='clients.client', verbose_name='client')),
            ],
            options={
                'verbose_name_plural': 'vacancies',
                'ordering': ['client__name', 'title'],
            },
        ),
    ]
