# Generated by Django 6.1.1 on 2026-10-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vacancy',
            options={'ordering': ['client__name', 'title'], 'verbose_name': 'vacancy', 'verbose_name_plural': 'vacancies'},
        ),
        migrations.AddField(
            model_name='vacancy',
            name='address',
            field=models.CharField(blank=True, help_text='Work location, used to calculate travel distance', max_length=200, verbose_name='address / postcode'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='client_pays_travel',
            field=models.BooleanField(default=False, help_text='Travel costs are then left out of the tariff', verbose_name='client pays travel costs'),
        ),
    ]
