# Generated by Django 6.1.1 on 2026-10-02 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_vacancy_options_vacancy_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancy_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'vacancy draft',
                'verbose_name_plural': 'vacancy drafts',
                'ordering': ['-updated_at'],
                'abstract': False,
            },
        ),
    ]
