# Generated by Django 6.1.1 on 2026-10-01 10:23

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='first name')),
                ('last_name', models.CharField(max_length=100, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='phone')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='city')),
                ('desired_role', models.CharField(blank=True, max_length=150, verbose_name='desired role')),
                ('status', models.CharField(choices=[('intake', 'Intake'), ('available', 'Available'), ('proposed', 'Proposed'), ('placed', 'Placed'), ('inactive', 'Inactive')], default='intake', max_length=20, verbose_name='status')),
                ('expected_salary_month', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='expected gross salary / month (€)')),
                ('hours_per_week', models.PositiveSmallIntegerField(default=40, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)], verbose_name='hours per week')),
                ('travel_known', models.BooleanField(default=False, verbose_name='travel details known')),
                ('travel_distance_km', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='distance one way (km)')),
                ('transport_type', models.CharField(choices=[('car', 'Car'), ('ov', 'Public transport'), ('bike', 'Bike'), ('none', 'None / unknown')], default='none', max_length=10, verbose_name='transport')),
                ('remote_days_per_week', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5)], verbose_name='remote days / week')),
                ('vacation_days', models.PositiveSmallIntegerField(default=25, verbose_name='vacation days / year')),
                ('sick_days_estimate', models.PositiveSmallIntegerField(default=8, verbose_name='expected sick days / year')),
                ('secondary_benefits_month', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='secondary benefits / month (€)')),
                ('benefits_description', models.CharField(blank=True, max_length=255, verbose_name='benefits description')),
                ('cost_factor', models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=4, verbose_name='cost factor')),
                ('margin_per_hour', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=6, verbose_name='margin / hour (€)')),
                ('proposed_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Leave empty to use the advised rate.', max_digits=7, null=True, verbose_name='proposed rate / hour (€)')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vacancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='clients.vacancy', verbose_name='vacancy')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
