# Generated by Django 6.1.1 on 2026-10-01 11:22

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def forwards(apps, schema_editor):
    """Travel only counted when travel_known was set; 'none'/'bike' are no longer travel means."""
    Candidate = apps.get_model("candidates", "Candidate")
    Candidate.objects.filter(travel_known=False).update(travel_distance_km=None)
    Candidate.objects.exclude(transport_type__in=["car", "ov"]).update(transport_type="car", travel_distance_km=None)


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards, migrations.RunPython.noop),
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ['-created_at'], 'verbose_name': 'candidate', 'verbose_name_plural': 'candidates'},
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='benefits_description',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='secondary_benefits_month',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='sick_days_estimate',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='travel_known',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='vacation_days',
        ),
        migrations.AlterField(
            model_name='candidate',
            name='city',
            field=models.CharField(blank=True, help_text='City, postcode or address, used to calculate travel distance', max_length=150, verbose_name='home location'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='cost_factor',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=4, verbose_name='cost price factor'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='expected_salary_month',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='desired gross salary / month (€)'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='hours_per_week',
            field=models.PositiveSmallIntegerField(default=40, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)], verbose_name='desired hours per week'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='margin_per_hour',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('5')), django.core.validators.MaxValueValidator(Decimal('15'))], verbose_name='margin / hour (€)'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='proposed_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Leave empty to use the advised tariff.', max_digits=7, null=True, verbose_name='proposed tariff / hour (€)'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='remote_days_per_week',
            field=models.PositiveSmallIntegerField(default=0, help_text='Used for matching only', validators=[django.core.validators.MaxValueValidator(5)], verbose_name='remote days / week'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='transport_type',
            field=models.CharField(choices=[('car', 'Car'), ('ov', 'Public transport')], default='car', max_length=10, verbose_name='travel means'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='travel_distance_km',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Calculated automatically from the home location and the vacancy location', max_digits=6, null=True, verbose_name='travel distance one way (km)'),
        ),
    ]
