# Generated by Django 6.1.1 on 2026-10-01 14:23

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_alter_candidate_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='margin_per_hour',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('25.00'))], verbose_name='margin / hour (€)'),
        ),
    ]
