# Generated by Django 6.1.1 on 2026-10-01 14:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_margin_range_0_25'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'candidate draft',
                'verbose_name_plural': 'candidate drafts',
                'ordering': ['-updated_at'],
            },
        ),
    ]
