# Generated by Django 6.1.1 on 2026-10-01 15:00

from django.db import migrations, models


def copy_from_vacancy(apps, schema_editor):
    """Existing candidates keep the price they had: the flag used to come from their vacancy."""
    Candidate = apps.get_model("candidates", "Candidate")
    Candidate.objects.filter(vacancy__client_pays_travel=True).update(client_pays_travel=True)


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_candidatedraft'),
        ('clients', '0002_alter_vacancy_options_vacancy_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='client_pays_travel',
            field=models.BooleanField(default=False, help_text="Travel costs are then left out of the tariff (defaults to the vacancy's setting)", verbose_name='client pays travel costs'),
        ),
        migrations.RunPython(copy_from_vacancy, migrations.RunPython.noop),
    ]
