# Generated by Django 6.1.1 on 2026-10-02 07:59

import django.db.models.deletion
from django.db import migrations, models


def copy_vacancy_to_link(apps, schema_editor):
    Candidate = apps.get_model("candidates", "Candidate")
    CandidateVacancy = apps.get_model("candidates", "CandidateVacancy")
    CandidateVacancy.objects.bulk_create([
        CandidateVacancy(
            candidate=c, vacancy_id=c.vacancy_id, travel_distance_km=c.travel_distance_km,
            client_pays_travel=c.client_pays_travel, proposed_rate=c.proposed_rate,
            status="placed" if c.status == "placed" else "proposed" if c.status == "proposed" else "considered",
        )
        for c in Candidate.objects.exclude(vacancy=None)
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_candidate_client_pays_travel'),
        ('clients', '0002_alter_vacancy_options_vacancy_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('considered', 'Considered'), ('proposed', 'Proposed'), ('placed', 'Placed'), ('rejected', 'Rejected')], default='considered', max_length=20, verbose_name='status')),
                ('travel_distance_km', models.DecimalField(blank=True, decimal_places=1, help_text='Calculated automatically from the home location and the vacancy location', max_digits=6, null=True, verbose_name='travel distance one way (km)')),
                ('client_pays_travel', models.BooleanField(default=False, help_text="Travel costs are then left out of the tariff (defaults to the vacancy's setting)", verbose_name='client pays travel costs')),
                ('proposed_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Leave empty to use the advised tariff.', max_digits=7, null=True, verbose_name='proposed tariff / hour (€)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='candidates.candidate')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_links', to='clients.vacancy', verbose_name='vacancy')),
            ],
            options={
                'verbose_name': 'candidate vacancy',
                'verbose_name_plural': 'candidate vacancies',
                'ordering': ['created_at', 'pk'],
            },
        ),
        # The old single vacancy (and its travel settings) becomes the candidate's first link
        migrations.RunPython(copy_vacancy_to_link, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='candidate',
            name='vacancy',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='client_pays_travel',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='proposed_rate',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='travel_distance_km',
        ),
        migrations.AddField(
            model_name='candidate',
            name='vacancies',
            field=models.ManyToManyField(related_name='candidates', through='candidates.CandidateVacancy', to='clients.vacancy', verbose_name='vacancies'),
        ),
        migrations.AddConstraint(
            model_name='candidatevacancy',
            constraint=models.UniqueConstraint(fields=('candidate', 'vacancy'), name='unique_candidate_vacancy'),
        ),
    ]
