# Generated by Django 6.1.1 on 2026-10-02 12:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0006_multi_vacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='travel_per_hour_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='travel costs / hour (€)'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='transport_type',
            field=models.CharField(choices=[('car', 'Car'), ('ov', 'Public transport'), ('manual', 'Manual')], default='car', max_length=10, verbose_name='travel means'),
        ),
    ]
